/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/app/**/*.{js,jsx,ts,tsx}",
    "./src/components/**/*.{js,jsx,ts,tsx}",
    "./src/screens/**/*.{js,jsx,ts,tsx}",
    "./src/constant/**/*.{js,jsx,ts,tsx}",
  ],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        green: "#2ECC71",
        "green-deep": "#1E8449",
        "green-tint": "#EAFBF1",
        "green-line": "#CDEFDC",
        amber: "#F39C12",
        "amber-tint": "#FEF3E2",
        "amber-deep": "#9A6208",
        "amber-deep-2": "#7A4E05",
        coral: "#E74C3C",
        "coral-tint": "#FDEDEA",
        "coral-deep": "#B23324",
        "coral-deep-2": "#8C2A1E",
        ink: "#16241C",
        "ink-soft": "#2D3C34",
        muted: "#4F5F56",
        line: "#E7EDE9",
        white: "#FFFFFF",
        canvas: "#F0F5F2",
        card: "#F8FAF9",
        blue: "#5FA8E0",
        violet: "#8B5CF6",
        "violet-tint": "#F0EDFF",
        "violet-deep": "#6D3ADE",
      },
      fontFamily: {
        display: ["Fraunces_600SemiBold"],
        "display-italic": ["Fraunces_500Medium_Italic"],
        sans: ["Inter_400Regular"],
        "sans-medium": ["Inter_500Medium"],
        "sans-semibold": ["Inter_600SemiBold"],
        "sans-bold": ["Inter_700Bold"],
        "sans-extrabold": ["Inter_800ExtraBold"],
      },
    },
  },
  plugins: [],
};